#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker12"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "6fc52ae162dd4b2f9c2b8503baa47b1c" }
]

[assets]
directory = "./public"
